AWSTemplateFormatVersion: '2010-09-09'
Description: Create a Secrets Manager secret for DB credentials

Parameters:
  SecretName:
    Type: String
    Description: Name for the Secrets Manager secret
    Default: ""
  DBUsername:
    Type: String
    Description: Database username
    Default: ""
  DBPassword:
    Type: String
    Description: Database password
    NoEcho: true
    Default: ""
  DBEndpoint:
    Type: String
    Description: Database endpoint
    Default: ""
  DBPort:
    Type: String
    Description: Database port
    Default: ""

    
Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: Secret for storing DB credentials
      # RotationRules: 
      # KmsKeyId:
      #   Ref: KmsKeyId
      SecretString:
        !Sub |
          {
            "username": "${DBUsername}",
            "password": "${DBPassword}",
            "endpoint": "${DBEndpoint}",
            "port": "${DBPort}"
          }
      Tags:
        - Key: Environment
          Value: Dev
        - Key: Application
          Value: costengine
Outputs:
  SecretARN:
    Description: The ARN of the created Secrets Manager secret
    Value: !Ref DBSecret